#!/usr/bin/env Rscript

#Taking in arguments
library("optparse")
 
option_list = list(
    make_option(c("-f", "--freq"), type="character", default=NULL, 
              help="annotated file generated by bedtools annotate", metavar="filetype"),
    make_option(c("-m", "--meta"), type="character", default=NULL, 
              help="order in which user prefers to visualize results. 1stcol:order number; 2ndcol:Filename; 3rdcol:Libraryname 4thcol:Cellline/Samplename, 5thcol:Replicate info", metavar="filetype"),
    make_option(c("-n", "--names"), type="integer", default=6, 
              help="column in metadata that matches the header in normalized frequency file [default %default] ", metavar="integer"),
    make_option(c("-b", "--baseline"), type="character", default=0.25, 
              help="expected frequency in the heatmap. Should be 0.25 if the group is of 4, 1/16 if group of 16 [default %default] "),
    make_option(c("-u", "--usebascol"), type="integer", default=0, 
              help="column number to used as baseline [default %default] "),
    make_option(c("-g", "--groupcol"), type="integer", default=4, 
              help="column in metadata that contains group info [default %default] ", metavar="integer"),
    make_option(c("-o", "--output_file"), type="character", default=NULL, 
              help="output file name with location", metavar="filetype")
); 

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

#Checking for required input
writeLines("\n...Checking input...\n")
if (is.null(opt$freq)){
  print_help(opt_parser)
  stop("Please specify normalized ratio file.n", call.=FALSE)
}

if (is.null(opt$meta)){
  print_help(opt_parser)
  stop("Please specify mtadata file.n", call.=FALSE)
}

baseline=as.numeric(opt$baseline)
#####Main Script
#1.Calling required Packages
writeLines("\n...Calling required Package(s)...\n")

#2.Read files
writeLines("\n...Processing input file(s)...\n")
df<-read.table(opt$freq, sep="\t", header =T,row.names=1, quote="", check.names=FALSE)
order=read.table(opt$meta, sep="\t",header = F, quote="")
rownames(order)<-order[,opt$names]
u=opt$usebascol
#3.Calculating Mann whitney P-values
writeLines("\n...Calculating pvalues with baseline reference...\n")
groups=order[rownames(order),][,opt$groupcol]
head=c('Comparisons',colnames(df))
#For all
add='all'
for (n in seq(1:ncol(df))) {
    if (u >= 1) {
        p=wilcox.test(df[,n],df[,u], alternative = c("greater"), exact=T)$p.value
    } else {
        p=wilcox.test(df[,n],rep(baseline,nrow(df)), alternative = c("greater"), exact=T)$p.value
    }
    add=c(add,p)
}
out=rbind(head, add)
#For celltypes
for (celltype in unique(groups)) {
    sub=df[groups==celltype,]
    add=celltype
    for (n in seq(1:ncol(sub))) {
        if (u >= 1) {
            p=wilcox.test(sub[,n],sub[,u], alternative = c("greater"), exact=T)$p.value
        } else {
            p=wilcox.test(sub[,n],rep(baseline,nrow(sub)), alternative = c("greater"), exact=T)$p.value
        }
        add=c(add,p)
    }
    out=rbind(out, add)
}

writeLines("\n...Calculating pvalues between groups...\n")
combn=t(combn(unique(groups),2))

for (r in seq(1:nrow(combn))) {
    sub1=df[groups==combn[r,1],]
    sub2=df[groups==combn[r,2],]
    add=paste(combn[r,1],combn[r,2], sep=' vs ')
    for (n in seq(1:ncol(sub1))) {
        p=wilcox.test(sub1[,n],sub2[,n], exact=T)$p.value
        add=c(add,p)
    }
    out=rbind(out, add)
}

#3.Calculating Mann whitney P-values
writeLines("\n...Generating output files...\n")
write.table(data.frame(out), paste(opt$output_file,sep=""),sep="\t", row.names=F, col.names=F)


writeLines("\nJob Finished.\n")
writeLines(paste("\nOutput file name:", paste(opt$output_file,"\n", sep="")))
